go-openapi/spec

- expander.go
- expander_test.go
fixes [go-swagger/go-swagger #483](https://github.com/go-swagger/go-swagger/issues/483)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/go-openapi/spec/1)
> - keep track of parent refs better

- header.go
- header_test.go
Hi, I found the header should support vendor extensions, [read here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#header-object).
So I just have it added for you.
> Add vendor extensions support for header.

- expander.go
- expander_test.go
1. Add "ExpandOptions" to specify relative base to load extra spec files.
2. Add "options *ExpandOptions" parameter to ExpandSpec.
3. Update "resolveRef" function.
4. Fix typo "defintition" -> "definition".
closes go-openapi/validate#17
closes go-swagger/go-swagger#711
closes go-swagger/go-swagger#331
closes go-swagger/go-swagger#358
Signed-off-by: Peng Jingwen <pengsrc@icloud.com>
> Fix: Expand spec that contains file reference.

- swagger.go
- swagger_test.go
fixes https://github.com/go-swagger/go-swagger/issues/898
> omit definitions from json serialization when empty

- expander.go
- expander_test.go
- fixtures/expansion/missingItemRef.json
If a swagger spec has a missing ref, don't dereference a nil schema when expanding a schema.
> Fix panic expanding a spec when and a reference is nil

- swagger.go
When `SchemaOrStringArray` is nil, it should get marshaled as json `null` value.
> swagger: nil value should get marshaled as json null

- items.go
if VendorExtensible is in Item of the parameter
we may need to handle the info of the extensible vendor
> marshal unmarshal item of parameter with vendorExtensible

- items.go
Add an `Example` field to `SimpleSchema` to support [example values](https://swagger.io/docs/specification/adding-examples/).
From my limited understanding of OpenAPI and a quick perusal of the codebase, `SimpleSchema` seemed like the right place to put the example field; if there's a better place please let me know.
> Add Example field to SimpleSchema

- operation.go
Empty arrays habe meaning in this place and a are different from the field not being set.
Thy can be used to override global `security` settings.
Fixes https://github.com/go-swagger/go-swagger/issues/1281
> Don't drop empty arrays of operations security definitions

- operation.go
- operation_test.go
This fixes a regression introduced by #39.
Turns out `security: null` breaks the validator as it expected either no field at all or an array.
OperatioProperties now have a custom marshaller that ensures that:
1. empty slices are preserved as empty arrays in JSON
2. if Security is unset/nil the key is omitted in JSON
> Avoid null value when serializing operations

- expander.go
Note that **I am not sure** that this is the correct way to fix the issue (and if this fix does not break anything) because I am not familiar with #38 changes.
But at least my code that I wrote before #38 finally works after this fix.
---
Fixes #45
Signed-off-by: Igor Zibarev <zibarev.i@gmail.com>
> Fix expandSchema when basePath is empty

- expander.go
The ExpandSchema() method calls ioutil.TempFile(), which creates a temporary file, and the file is not deleted before program termination. As specified in the golang documentation, it is the caller's responsibility to delete temporary files created by ioutil.TempFile()
> 47-Delete temporary files before program termination

- expander.go
clean up temp files in ExpandSchema()
fixes go-openapi/spec#47
> clean up temp files

- expander.go
- fixtures/expansion/missingRef.json
- When ref has a fragment only or is pointing to root and root is nil then resolve against the root
- can expand schema without a base path
- speed up spec expansion
> - Don't write root schema to disk.

- expander.go
- expander_test.go
The validate package needs these functions from the spec package to be able to properly expand response and parameter objects
> added exported versions of expandResponse() and expandParameter()

- expander.go
the cache is queried by normalized key.
but in ExpandSchema(), root was stored with un-normalized key.
this causes trouble on Windows which have drive letter as upper case in
absolute path.  when normalize this absolute path, drive letter is converted
to lower case.  and it causes cache miss and ExpandSchema() failure.
> normalize cache key for root in ExpandSchema

- ref.go
- schema.go
- schema_test.go
and add some benchmarks. This is a bottleneck for the kubernetes unit tests.
The fix works by caching the deserialization of the full schema into a
map. We were doing this three times. Now we only do it once.
Before:
```    
BenchmarkSchemaUnmarshal-12
50000            321498 ns/op           86325 B/op       1400 allocs/op
```
After:
```    
BenchmarkSchemaUnmarshal-12
100000            131877 ns/op           46183 B/op        535 allocs/op
```
@mbohlool
> improve performance of schema deserialize

- expander.go
- expander_test.go
This is a fix for the issues: https://github.com/go-openapi/spec/issues/66, https://github.com/go-openapi/spec/issues/63, https://github.com/go-openapi/spec/issues/64
Probably this doesn't fix: https://github.com/go-openapi/spec/issues/65
> resolver cache setting fix for Windows, normalize and tests

- expander.go
- fixtures/bugs/1429/remote/remote.yaml
- fixtures/bugs/1429/remote/remote/remote.yaml
- fixtures/bugs/1429/responses.yaml
- fixtures/bugs/1429/swagger.yaml
- spec_test.go
- Contributes to go-swagger/go-swagger#1429
- Fixes #77 
This fixes the case when SkipSchema:true, there are remote $ref in
in schema for params and responses declared themselves with $ref (!)
> Relocate relative $ref in response and param schema

- .golangci.yml
- debug.go
- debug_test.go
- expander.go
- expander_test.go
- fixtures/bugs/957/fixture-957.json
- fixtures/expansion/circular-minimal.json
- fixtures/expansion/circularSpec2.json
This PR is not fully satisfying in the sense that it does not fix once and for all the
circular ref story. It improves spec expansion which no more hangs on some complex
circular ref patterns. However, it is not able to produce stable expanded schemas when it
used to hang.
All produced expansions are _correct_, but may vary in the way they expand cycles,
when several cycles do collide. Since we walk the spec at random and this spec is mutating
during the expansion process, we stand no chance to come out with a clean resolution
(i.e. resolve shortest cycles first)
What it does:
* Fixes #76 (absolute path left behind in resolved circular $ref)
* Fixes #74 (isCircular no more checks on basePath!="")
* Contributes #75 (hang is solved, but the (always correct) expanded result may differ from …
> Hang when expanding circular $ref

- .golangci.yml
- expander.go
- expander_test.go
- fixtures/bugs/1614/gitea.json
- fixtures/bugs/1621/definitions.yaml
- fixtures/bugs/1621/fixture-1621.yaml
- fixtures/bugs/1621/parameters.yaml
- fixtures/bugs/1621/responses.yaml
- spec_test.go
* Added option to expand circular $ref with absolute path
This option is selected by default when expanding with a root schema
instead of a BasePath
* Added ExpandResponseWithRoot() and ExpandParameterWithRoot() to cover the validate use case
* Fixed relative path issue in ExpandResponse() and ExpandParameter() (failed to resolve $ref when resolved
in another location than .)
* Contributes go-swagger/go-swagger#1614
* Contributes go-swagger/go-swagger#1621
> optional absolute path in circular $ref

- ref.go
- ref_test.go
Fix regression on unmarshalling Ref types by using gob encode/decode
* Contributes go-swagger/go-swagger#1816
> Fix go-swagger/go-swagger#1816

- items.go
- schema.go
Towards v3 support, we have to add nullable, as an alternative to the JSON-Schema inspired `null` type.
Note, that both are not 100% the same as `type:"", nullable:true` is a valid construct which cannot be faithfully represented with the `null` type only.
> Add nullable

- .golangci.yml
- expander.go
- fixtures/bugs/2113/base.yaml
- fixtures/bugs/2113/schemas/api/api.yaml
- fixtures/bugs/2113/schemas/dummy/dummy.yaml
- fixtures/bugs/2113/schemas/example/example.yaml
- ref.go
- schema_loader.go
- spec_test.go
Fixes ref rebasing when following nested $ref in Paths section
> contributes go-swagger/go-swagger#2113

- expander.go
- expander_test.go
- fixtures/more_circulars/resp.json
- schema_loader.go
During root expansion without base, the doc gets loaded by fake absolute path key to the cache, but during resolve it tries to load the doc with just "root" key.
this contributes to https://github.com/go-openapi/spec/issues/95
> Get root from cache by a correct key

- parameter.go
- parameters_test.go
Hello, as i understand.
When parameter object's in is `body`, should not has property `type`.
> bugfix: remove type from body parameter object.

- go.mod
- go.sum
Upgrade to latest version of github.com/go-openapi/swag
> Upgrade to latest version of github.com/go-openapi/swag

- .travis.yml
* rolled over golang versions
* re-enacted linter in CI (golangci no more operates as a ci provider)
* reduced job expansion for ppc arch job
* run go-openapi/analysis tests to avoid introducing breaking changes
> ci configuration update

- README.md
- bindata.go
- contact_info.go
- license.go
- properties.go
- spec_test.go
* removed golangci badge
* made it explicit the repo won't support swagger 3
* closes #21
> Updated the project's README

- cache.go
- expander.go
- expander_test.go
- operation.go
- schema_loader.go
- spec.go
The point with this PR is to avoid unnecessary memory requirements on packages importing this package because of some dependency but do not actually use its full functionality.
Most memory initialization is required by the expander so let’s allocate it only when required.
* moved default cache initialization from init() to on-demand initializer wrapped in sync.Once.Do
* removed unused jsonSchema & swaggerSchema initialized globals
* replaced PathLoader init() by lazy var initialization
> Reduce memory usage at package init time

- expander.go
- fixtures/bugs/102/fixture-102.json
- spec_test.go
Covers case with ExpandResponseWithRoot and ExpandParameterWithRoot
* acknowledged github.com/go-openapi/validate#102 is fixed
* extended this use case of circular references to the "WithRoot" functions and fixed issues with those
* fixes #95
> fixed case of circular references

- header.go
- header_test.go
- items.go
- items_test.go
- parameter.go
- parameters_test.go
- schema.go
- schema_test.go
- validations.go
- validations_test.go
This only adds things and does not alter the exposed interface or types.
* supersedes #100 
> added helpers to manipulate validation in schemas and simple schemas

- schema_loader.go
Possible fix for issue: go-swagger throws error on Windows if application path contains parentheses #145
> go-swagger throws error on Windows if application path contains parentheses 

- normalizer_test.go
Signed-off-by: Youyuan Wu <youyuanwu@outlook.com>
Failed tests on master:
```
--- FAIL: TestNormalizer_NormalizeBase (0.00s)
--- FAIL: TestNormalizer_NormalizeBase//base/sub/file.json (0.00s)
normalizer_test.go:[41](https://github.com/go-openapi/spec/runs/7816924392?check_suite_focus=true#step:4:42)8: 
Error Trace:	normalizer_test.go:418
Error:      	Not equal: 
expected: "file:///c:/base/sub/file.json"
actual  : "file:///d:/base/sub/file.json"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-file:///c:/base/sub/file.json
+file:///d:/base/sub/file.json
Test:       	TestNormalizer_NormalizeBase//base/sub/file.json
Messages:   	for base "/base/sub/file.json"
--- FAIL: TestNormalizer_NormalizeBase//.. (0.00s)
normalizer_test.go:418: 
Error Trace:	normalizer_test.go:418
Error:      	Not equal: …
```
> Fix failed windows tests that depends on cwd

- .golangci.yml
- circular_test.go
- contact_info_test.go
- expander.go
- expander_test.go
- header_test.go
- helpers_spec_test.go
- helpers_test.go
- info_test.go
- items_test.go
- license_test.go
- normalizer_nonwindows.go
- normalizer_test.go
- operation.go
- operation_test.go
- parameter.go
- parameters_test.go
- path_item_test.go
- paths_test.go
- ref_test.go
- resolver_test.go
- response_test.go
- responses_test.go
- schema_test.go
- spec.go
- structs_test.go
- swagger_test.go
- validations_test.go
- xml_object_test.go
* updated linter config
* refactored tests: if !assert => require
* fixed a few other linting issues other than test code: x := append(y, z...), typos
> chore: updated linting config, relinted

- .github/workflows/go-test.yml
* re-enacted golangci-lint run in github action
* re-enacted codecov uploads in github action
> ci: re-enacted linting

- expander.go
- fixtures/bugs/2743/not-working/minimal.yaml
- fixtures/bugs/2743/not-working/spec.yaml
- fixtures/bugs/2743/not-working/swagger/definitions.yml
- fixtures/bugs/2743/not-working/swagger/items.yml
- fixtures/bugs/2743/not-working/swagger/paths/bar.yml
- fixtures/bugs/2743/not-working/swagger/paths/foo.yml
- fixtures/bugs/2743/not-working/swagger/paths/index.yml
- fixtures/bugs/2743/not-working/swagger/paths/nested.yml
- fixtures/bugs/2743/not-working/swagger/user/index.yml
- fixtures/bugs/2743/not-working/swagger/user/model.yml
- fixtures/bugs/2743/working/spec.yaml
- fixtures/bugs/2743/working/swagger/definitions.yml
- fixtures/bugs/2743/working/swagger/items.yml
- fixtures/bugs/2743/working/swagger/paths/bar.yml
- fixtures/bugs/2743/working/swagger/paths/foo.yml
- fixtures/bugs/2743/working/swagger/paths/index.yml
- fixtures/bugs/2743/working/swagger/paths/nested.yml
- fixtures/bugs/2743/working/swagger/user/index.yml
- fixtures/bugs/2743/working/swagger/user/model.yml
- spec_test.go
* fixes #182
* contributes go-swagger/go-swagger#2743
> fix(expand): parameters & responses should properly follow remote doc resolution when SKipSchema

- README.md
These discussion threads are valuable, but no longer active.
* fixes #164
* fixes #23
> doc(faq): transferred questions to README
