go-openapi/spec

- expander.go
- expander_test.go
- fixtures/expansion/overflow.json
Fixes #3 
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/go-openapi/loads/4)
> Fix circular ref panics

- operation.go
- operation_test.go
- path_item.go
- path_item_test.go
- responses.go
- security_scheme.go
- tag.go
> Make all embedded structs public

- expander.go
> update-jsonschema 

- ref.go
Noticed it in the godoc so thought I'll send a fix! :)
> ref: fix comment for MustCreateRef

- expander.go
- refmodifier.go
- refmodifier_test.go
> Reference Resolution

- expander.go
- expander_test.go
modifying normalizePaths to work with windows paths as well
> fixing paths for windows

- expander.go
Fixes #43
Signed-off-by: Igor Zibarev <zibarev.i@gmail.com>
> Consistently check if RelativeBase is empty

- expander.go
> Revert "47-Delete temporary files before program termination"

- expander.go
- expander_test.go
- fixtures/remote/all-the-things.json
- fixtures/remote/pet/pet.json
- will expand responses, path items, and parameters recursively
- supports base paths for responses, path items, and parameters
> fix expand response, path items, and parameters

- expander.go
- expander_test.go
- fixtures/specs/todos.common.json
- fixtures/specs/todos.json
> Support Transitive Refs

- .travis.yml
Upgrade CI conf
Looks like net/url is outdated with 1.7
> upgrade CI with go 1.8 and 1.9

- expander.go
- don't prematurely add a parentRef when expanding a response/parameter
- handle transitive refs for responses/parameters
> Handle circular refs for responses/parameters schemas.

- .golangci.yml
- info_test.go
- operation.go
- operation_test.go
- parameters_test.go
> Fix gob encoding on operations

- appveyor.yml
Just avoiding blocking all PRs until #97 is fixed.
> temporarily disable appveyor CI

- expander.go
- expander_test.go
- license_test.go
- operation.go
- operation_test.go
- ref.go
> relint by latest golangci settings

- expander.go
- expander_test.go
- fixtures/more_circulars/remote/tree
- fixtures/more_circulars/with-id.json
- normalizer.go
> Resolve circular references created with schema ID

- expander.go
- expander_test.go
- fixtures/expansion/crossFileRef.json
Applies #128 after fixing linting issues
> Expand param with base

- schema_loader.go
> removed debug

- README.md
> fixed README: typo, new URL to pkg.go.dev

- normalizer.go
- normalizer_nonwindows.go
- normalizer_windows.go
- schema.go
- url_go18.go
- url_go19.go
Closes: #157
Signed-off-by: Shengjing Zhu <zhsj@debian.org>
> preserve url.Parse behaviour before go1.19

- info.go
- properties.go
> Fix `x-order` not working with number value #162
